const progress = document.querySelector('.progress span');
const updateProgress = () => { const max = document.documentElement.scrollHeight - innerHeight; progress.style.width = `${max ? (scrollY / max) * 100 : 0}%`; };
addEventListener('scroll', updateProgress, { passive: true }); updateProgress();
const observer = new IntersectionObserver(entries => entries.forEach(entry => { if (entry.isIntersecting) { entry.target.classList.add('visible'); observer.unobserve(entry.target); } }), { threshold: .13 });
document.querySelectorAll('.reveal').forEach(el => observer.observe(el)); document.querySelector('#year').textContent = new Date().getFullYear();

document.querySelectorAll('.hero-title h1').forEach(el => el.dataset.cyber = el.textContent.trim());
const canvas = document.createElement('canvas'); canvas.className = 'cyber-matrix'; canvas.setAttribute('aria-hidden','true'); document.body.prepend(canvas);
['cyber-noise','cyber-scan','cyber-cursor','cyber-trail'].forEach(name => { const el = document.createElement('div'); el.className = name; el.setAttribute('aria-hidden','true'); document.body.append(el); });
const ctx = canvas.getContext('2d'); let drops = [], cell = 18;
function resizeMatrix(){ const ratio = devicePixelRatio; canvas.width=innerWidth*ratio; canvas.height=innerHeight*ratio; ctx.setTransform(ratio,0,0,ratio,0,0); cell=innerWidth<700?15:18; drops=Array(Math.ceil(innerWidth/cell)).fill(0).map(()=>Math.random()*-45); }
function rain(){ ctx.fillStyle='rgba(5,8,6,.08)'; ctx.fillRect(0,0,innerWidth,innerHeight); ctx.fillStyle='#b9ff45'; ctx.font=`${cell-3}px DM Mono`; drops.forEach((drop,i)=>{ if(Math.random()>.48)ctx.fillText('01アイウエオ'.charAt(Math.floor(Math.random()*7)),i*cell,drop*cell); if(drop*cell>innerHeight&&Math.random()>.978)drops[i]=0; drops[i]+=.34; }); requestAnimationFrame(rain); }
resizeMatrix(); rain(); addEventListener('resize',resizeMatrix);
if(matchMedia('(pointer:fine)').matches){const cursor=document.querySelector('.cyber-cursor'),trail=document.querySelector('.cyber-trail');let tx=0,ty=0,cx=0,cy=0;addEventListener('mousemove',e=>{tx=e.clientX;ty=e.clientY;cursor.style.left=`${tx}px`;cursor.style.top=`${ty}px`});const follow=()=>{cx+=(tx-cx)*.16;cy+=(ty-cy)*.16;trail.style.left=`${cx}px`;trail.style.top=`${cy}px`;requestAnimationFrame(follow)};follow();document.querySelectorAll('a').forEach(el=>{el.addEventListener('mouseenter',()=>{cursor.classList.add('active');trail.classList.add('active')});el.addEventListener('mouseleave',()=>{cursor.classList.remove('active');trail.classList.remove('active')});el.addEventListener('mousemove',e=>{const r=el.getBoundingClientRect(),x=(e.clientX-r.left-r.width/2)*.12,y=(e.clientY-r.top-r.height/2)*.12;el.style.transform=`translate(${x}px,${y}px)`});el.addEventListener('mouseleave',()=>el.style.transform='')})}
document.querySelectorAll('.hero-title,.orb-one,.orb-two').forEach((el,i)=>addEventListener('scroll',()=>{const rate=[.055,-.1,.08][i];el.style.transform=`translateY(${(el.getBoundingClientRect().top-innerHeight/2)*rate}px)`},{passive:true}));